import random
from typing import List, Callable
from sirtet.cell import Segment
from sirtet.matrix import Mat, Matrix


class Shapes:

    def __init__(self):
        # self._shapes: List[Mat] = [Mat([[Segment(0), Segment(0), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(0), Segment(1), Segment(1)], ]),
        #                            Mat([[Segment(0), Segment(0), Segment(0)],
        #                                 [Segment(0), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(0)], ]),
        #                            Mat([[Segment(1), Segment(0), Segment(0)],
        #                                 [Segment(1), Segment(0), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(0)], ]),
        #                            Mat([[Segment(0), Segment(0), Segment(1)],
        #                                 [Segment(0), Segment(0), Segment(1)],
        #                                 [Segment(0), Segment(1), Segment(1)], ]),
        #                            Mat([[Segment(1), Segment(0), Segment(0)],
        #                                 [Segment(1), Segment(0), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(1)], ]),
        #                            Mat([[Segment(0), Segment(0), Segment(1)],
        #                                 [Segment(0), Segment(0), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(1)], ]),
        #                            Mat([[Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(0), Segment(0), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(1)], ]),
        #                            Mat([[Segment(0), Segment(0), Segment(1)],
        #                                 [Segment(0), Segment(1), Segment(1)],
        #                                 [Segment(0), Segment(0), Segment(1)], ]),
        #                            Mat([[Segment(0), Segment(0), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(0), Segment(0), Segment(1)], ]),
        #                            Mat([[Segment(1), Segment(0), Segment(1)],
        #                                 [Segment(0), Segment(1), Segment(1)],
        #                                 [Segment(0), Segment(0), Segment(1)], ]),
        #                            Mat([[Segment(0), Segment(0), Segment(1)],
        #                                 [Segment(0), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(0), Segment(1)], ]),
        #                            Mat([[Segment(0), Segment(1), Segment(0)],
        #                                 [Segment(0), Segment(1), Segment(0)],
        #                                 [Segment(0), Segment(1), Segment(0)], ]),
        #                            Mat([[Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(0)], ]),
        #                            Mat([[Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(0)], ]),
        #                            Mat([[Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(0)], ]),
        #                            Mat([[Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(1)], ]),
        #                            Mat([[Segment(1), Segment(0), Segment(0)],
        #                                 [Segment(0), Segment(1), Segment(0)],
        #                                 [Segment(0), Segment(0), Segment(1)], ]),
        #                            Mat([[Segment(1), Segment(0), Segment(1)],
        #                                 [Segment(0), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(0), Segment(1)], ]),
        #                            Mat([[Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(1)], ]),
        #                            Mat([[Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(1)], ]),
        #                            Mat([[Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(0)], ]),
        #                            Mat([[Segment(0), Segment(0), Segment(0)],
        #                                 [Segment(0), Segment(1), Segment(0)],
        #                                 [Segment(0), Segment(0), Segment(0)], ]),
        #                            Mat([[Segment(0), Segment(0), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(0), Segment(0), Segment(0)], ]),
        #                            Mat([[Segment(1), Segment(0), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(0), Segment(0), Segment(0)], ]),
        #                            Mat([[Segment(0), Segment(0), Segment(0)],
        #                                 [Segment(1), Segment(1), Segment(0)],
        #                                 [Segment(1), Segment(0), Segment(0)], ]),
        #                            Mat([[Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(1)],
        #                                 [Segment(1), Segment(1), Segment(1)], ]), ]
        self._shapes: List[Callable[[], Mat]] = [lambda: Mat([[Segment(0), Segment(0), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(0)],
                                                              [Segment(0), Segment(1), Segment(1)], ]),
                                                 lambda: Mat([[Segment(0), Segment(0), Segment(0)],
                                                              [Segment(0), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(0)], ]),
                                                 lambda: Mat([[Segment(1), Segment(0), Segment(0)],
                                                              [Segment(1), Segment(0), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(0)], ]),
                                                 lambda: Mat([[Segment(0), Segment(0), Segment(1)],
                                                              [Segment(0), Segment(0), Segment(1)],
                                                              [Segment(0), Segment(1), Segment(1)], ]),
                                                 lambda: Mat([[Segment(1), Segment(0), Segment(0)],
                                                              [Segment(1), Segment(0), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(1)], ]),
                                                 lambda: Mat([[Segment(0), Segment(0), Segment(1)],
                                                              [Segment(0), Segment(0), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(1)], ]),
                                                 lambda: Mat([[Segment(1), Segment(1), Segment(1)],
                                                              [Segment(0), Segment(0), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(1)], ]),
                                                 lambda: Mat([[Segment(0), Segment(0), Segment(1)],
                                                              [Segment(0), Segment(1), Segment(1)],
                                                              [Segment(0), Segment(0), Segment(1)], ]),
                                                 lambda: Mat([[Segment(0), Segment(0), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(1)],
                                                              [Segment(0), Segment(0), Segment(1)], ]),
                                                 lambda: Mat([[Segment(1), Segment(0), Segment(1)],
                                                              [Segment(0), Segment(1), Segment(1)],
                                                              [Segment(0), Segment(0), Segment(1)], ]),
                                                 lambda: Mat([[Segment(0), Segment(0), Segment(1)],
                                                              [Segment(0), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(0), Segment(1)], ]),
                                                 lambda: Mat([[Segment(0), Segment(1), Segment(0)],
                                                              [Segment(0), Segment(1), Segment(0)],
                                                              [Segment(0), Segment(1), Segment(0)], ]),
                                                 lambda: Mat([[Segment(1), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(0)], ]),
                                                 lambda: Mat([[Segment(1), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(0)], ]),
                                                 lambda: Mat([[Segment(1), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(0)], ]),
                                                 lambda: Mat([[Segment(1), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(1)], ]),
                                                 lambda: Mat([[Segment(1), Segment(0), Segment(0)],
                                                              [Segment(0), Segment(1), Segment(0)],
                                                              [Segment(0), Segment(0), Segment(1)], ]),
                                                 lambda: Mat([[Segment(1), Segment(0), Segment(1)],
                                                              [Segment(0), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(0), Segment(1)], ]),
                                                 lambda: Mat([[Segment(1), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(1)], ]),
                                                 lambda: Mat([[Segment(1), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(1)], ]),
                                                 lambda: Mat([[Segment(1), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(0)], ]),
                                                 lambda: Mat([[Segment(0), Segment(0), Segment(0)],
                                                              [Segment(0), Segment(1), Segment(0)],
                                                              [Segment(0), Segment(0), Segment(0)], ]),
                                                 lambda: Mat([[Segment(0), Segment(0), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(0)],
                                                              [Segment(0), Segment(0), Segment(0)], ]),
                                                 lambda: Mat([[Segment(1), Segment(0), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(0)],
                                                              [Segment(0), Segment(0), Segment(0)], ]),
                                                 lambda: Mat([[Segment(0), Segment(0), Segment(0)],
                                                              [Segment(1), Segment(1), Segment(0)],
                                                              [Segment(1), Segment(0), Segment(0)], ]),
                                                 lambda: Mat([[Segment(1), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(1)],
                                                              [Segment(1), Segment(1), Segment(1)], ]), ]

    def dim(self) -> int:
        return len(self._shapes)

    def get(self, index: int=None) -> Mat:
        index = random.randint(0, self.dim() - 1) if index is None else index
        return self._shapes[index]()


class Generator:

    def __init__(self):
        self.shapes: Shapes = Shapes()

    def get_next(self) -> Matrix:
        return Matrix(self.shapes.get())


if __name__ == '__main__':
    s = Shapes()
    for x in s._shapes:
        print(Matrix(x()))
        print()
